# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/top_module/top_module.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_module || ORIG_REF_NAME==top_module} -quiet] -quiet

# IP: bd/top_module/ip/top_module_processing_system7_0_3/top_module_processing_system7_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_module_processing_system7_0_3 || ORIG_REF_NAME==top_module_processing_system7_0_3} -quiet] -quiet

# IP: bd/top_module/ip/top_module_axi_dma_0_2/top_module_axi_dma_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_module_axi_dma_0_2 || ORIG_REF_NAME==top_module_axi_dma_0_2} -quiet] -quiet

# IP: bd/top_module/ip/top_module_xbar_2/top_module_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_module_xbar_2 || ORIG_REF_NAME==top_module_xbar_2} -quiet] -quiet

# IP: bd/top_module/ip/top_module_auto_pc_0/top_module_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_module_auto_pc_0 || ORIG_REF_NAME==top_module_auto_pc_0} -quiet] -quiet

# IP: bd/top_module/ip/top_module_ps7_0_axi_periph_2/top_module_ps7_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_module_ps7_0_axi_periph_2 || ORIG_REF_NAME==top_module_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/top_module/ip/top_module_rst_ps7_0_100M_2/top_module_rst_ps7_0_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_module_rst_ps7_0_100M_2 || ORIG_REF_NAME==top_module_rst_ps7_0_100M_2} -quiet] -quiet

# IP: bd/top_module/ip/top_module_xbar_3/top_module_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_module_xbar_3 || ORIG_REF_NAME==top_module_xbar_3} -quiet] -quiet

# IP: bd/top_module/ip/top_module_auto_us_0/top_module_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_module_auto_us_0 || ORIG_REF_NAME==top_module_auto_us_0} -quiet] -quiet

# IP: bd/top_module/ip/top_module_auto_us_1/top_module_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_module_auto_us_1 || ORIG_REF_NAME==top_module_auto_us_1} -quiet] -quiet

# IP: bd/top_module/ip/top_module_auto_pc_1/top_module_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_module_auto_pc_1 || ORIG_REF_NAME==top_module_auto_pc_1} -quiet] -quiet

# IP: bd/top_module/ip/top_module_axi_mem_intercon_1/top_module_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_module_axi_mem_intercon_1 || ORIG_REF_NAME==top_module_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/top_module/ip/top_module_top_0_2/top_module_top_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_module_top_0_2 || ORIG_REF_NAME==top_module_top_0_2} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# XDC: /home/yinchian/Univ_Proj_Local/university_project/the_legend_of_our_main/the_legend_of_our_main.gen/sources_1/bd/design_1/design_1_ooc.xdc

# XDC: /home/yinchian/Univ_Proj_Local/university_project/the_legend_of_our_main/the_legend_of_our_main.gen/sources_1/bd/design_1/design_1_ooc.xdc

# XDC: /home/yinchian/Univ_Proj_Local/university_project/the_legend_of_our_main/the_legend_of_our_main.gen/sources_1/bd/top_module/top_module_ooc.xdc
